lojaapp/urls.py
from django.urls import path
from.views import *


app_name = "lojaapp"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("sobre/", SobreView.as_view(), name="sobre"),
    path("contato/", ContatoView.as_view(), name="contato"),
    path("todos-produtos/", ToddosProdutosView.as_view(), name="Todosprodutos"),
    path("produto/<slug:slug>/", ProdutoDetalheView.as_view(), name="produtodetalhe"),
    path("addcarro-<int:pro_id>/", AddCarroView.as_view(), name="addcarro"),
    path("meu-carro/", MeuCarroView.as_view(), name="meucarro"),
    path("manipular-carro/<int:cp_id>/", ManipularCarroView.as_view(), name="manipularcarro"),
    path("limpar-carro/", LimparCarroView.as_view(), name="limparcarro"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
]

lojaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("lojaapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojaapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_competo = models.CharField(max_length=200)
    endereco = models.CharField(max_length=200, null=True, blank=True)
    data_on = models.DateField(auto_now_add=True)
    cpf_cnpj = models.CharField(max_length=20, null=True, blank=True)
    ie_rg = models.CharField(max_length=20, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.nome_competo
    

class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.titulo
    
class Produto(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    image = models.ImageField(upload_to="produtos")
    mercado = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    venda = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    descricao = models.TextField()
    garantia = models.CharField(max_length=300, null=True, blank=True)
    devolucao = models.CharField(max_length=300, null=True, blank=True)
    visualizacao = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.titulo

class Carro(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.SET_NULL, null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Carro:" +str(self.id)
    
class CarroProduto(models.Model):
    carro = models.ForeignKey(Carro,on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto,on_delete=models.CASCADE)
    avaliacao = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quantidade = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return "Carro:" + str (self.carro.id) + "CarroProduto:" + str (self.id)
    
PEDIDO_STATUS=(
    ("Pedido Recebido", "Pedido Recebido"),
    ("Pedido Processando", "Pedido Processando"),
    ("Pedido a Caminho", "Pedido a Caminho"),
    ("Pedido Completado", "Pedido Completado"),
    ("Pedido Cancelado", "Pedido Cancelado"),

)
    
class Pedido_order(models.Model):
    carro = models.OneToOneField(Carro, on_delete=models.CASCADE)
    ordenando_por = models.CharField(max_length=200)
    endereco_envio = models.CharField(max_length=200)
    telefone = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    endereco_envio = models.CharField(max_length=200)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    desconto = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    pedido_status = models.CharField(max_length=50, choices=PEDIDO_STATUS)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Pedido_order:" +str(self.id)
    

templates/addprocarro.html
{% extends 'base.html' %}

{% block title %}Carrinho{% endblock title %}

{% block content %}

<div class="container">
    Produto adicionado no carrinho com sucesso!!!
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

</head>
<body>
   <div class="container mt-3">
    <a class="btn btn-success" href="{% url 'lojaapp:home' %}">HOME</a> |
    <a class="btn btn-success" href="{% url 'lojaapp:sobre' %}">SOBRE</a> |
    <a class="btn btn-success" href="{% url 'lojaapp:contato' %}">CONTATO</a> |
    <a class="btn btn-success" href="{% url 'lojaapp:Todosprodutos' %}">CATEGORIAS</a> |
    <a class="btn btn-success" href="{% url 'lojaapp:meucarro' %}">CARRINHO</a>
    <hr>
   </div>
    {% block content %}

    {% endblock content %}
</body>
</html>

templates/contato.html
{% extends 'base.html' %}

{% block title %}Contato{% endblock title %}

{% block content %}

<h1>SEJA BEM VINDO A LOJA RR PARTNES E VESTUÁRIOS - CONTATOS </h1>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="container">
    <h2 class="text-center">SEJA BEM VINDO A LOJA RR PARTNES E VESTUÁRIOS - HOME </h2>
    <hr>
    <div class="row mt-3">
        {% for p in produto_list %}
            <div class="col-md-4">
                <div class="m-3">
                    <h8><a href="{% url 'lojaapp:produtodetalhe' p.slug %}">{{p.titulo}}</h8></a>
                    <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 150px; object-fit: cover;">
                    <P class="mt-3">Preço: <strike> R$ .{{p.mercado}}</strike> R$. {{p.venda}}</P>
                    <a href= "{% url 'lojaapp:addcarro' p.id%}" class="btn btn-success">Adcionar ao Carrinho</a>
                </div>
            </div>

        {% endfor %}

    </div>
</div>

{% endblock %}

templates/meucarro.html
{% extends 'base.html' %}

{% block title %}Meu Carrinho{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col md 8">
            <h4>Itens do Carrinho</h4>
            <table class="table">
                <thead>
                    <tr>
                       <th>Item</th>
                       <th>Produto</th>
                       <th>Valor Unitario</th>
                       <th>Quantidade</th>
                       <th>Subtotal</th>
                       <th>Ação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in carro.carroproduto_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.produto.titulo }}</td>
                        <td>{{ cp.avaliacao|floatformat:2 }}</td>
                        <td>{{ cp.quantidade }}</td>
                        <td>{{ cp.subtotal|floatformat:2 }}</td>
                        <td>
                            <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=inc" class="btn btn-success"> + </a>
                            <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=rmv" class="btn btn-danger"> X </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right" Total a pagar></th>
                        <th>R$: {{carro.total|floatformat:2}}</th>    
                         {% if carro.carroproduto_set.all %}              
                            <th><a href="{% url 'lojaapp:limparcarro' %}" class="btn btn-warning">Limpar Carrinho</a></th>
                        {% endif %}    
                    </tr>
                    {% if carro.carroproduto_set.all %}
                    <tr>                                    
                            <th><a href="{% url 'lojaapp:checkout' %}" class="btn btn-info">Processar Compra</a></th>                         
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/processar.html
{% extends 'base.html' %}
{% block title %}Processar Compra{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col md-6">
            <h4>Itens do Carrinho</h4>
            <table class="table">
                <thead>
                    <tr>
                       <th>Item</th>
                       <th>Produto</th>
                       <th>Valor Unitario</th>
                       <th>Quantidade</th>
                       <th>Subtotal</th>
                       <th>Ação</th>
                    </tr>
                </thead> 
                <tbody>
                    {% for cp in carro.carroproduto_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.produto.titulo }}</td>
                        <td>{{ cp.avaliacao|floatformat:2 }}</td>
                        <td>{{ cp.quantidade }}</td>
                        <td>{{ cp.subtotal|floatformat:2 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                   <tr>
                    <th colspan="4" class="text-right">Valor Total</th>
                    <th>R$:{{carro.total}}</th>
                </tr>
            </table>
            </div>           
        <div class="col md-6">
            <h3>Detalhes da Compra</h3>
        </div>
            <form action="">

            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/produtodetalhe.html
{% extends 'base.html' %}

{% block title %}{{produto.titulo}}{% endblock title %}

{% block content %}

<div class="container">

    <h4>Produto: {{produto.titulo}}</h4><hr>

<div class="row">
    <div class="col-md-6">
        <img src="{{produto.image.url}}" alt="" class="img-fluid" width="280px">
    </div>
    <div class="col-md-6">
        <h4>{{produto.titulo}} ( {{produto.visualizacao}} Visualizações)</h4>
        <h4>Categoria: {{produto.categoria}}</h4>
        <h5>Preço: <strike>R$ {{produto.mercado}}</strike> R$ {{produto.venda}}</h5>
        <a href="{% url 'lojaapp:addcarro' produto.id%}" class="btn btn-success">Adicionar ao Carrinho</a><hr>
        <p class="text-danger">Garantia: {{produto.garantia}}</p>
        <p class="text-danger">Devolução: {{produto.returm_devolucao}}</p>
        <p class="text-success">{{produto.descricao}}</p>
    </div>
</div>              
</div>
{% endblock %}

templates/sobre.html
{% extends 'base.html' %}

{% block title %}Sobre{% endblock title %}

{% block content %}

<h1>SEJA BEM VINDO A LOJA RR PARTNES E VESTUÁRIOS - SOBRE </h1>
        
{% endblock %}

templates/todosprodutos.html
{% extends 'base.html' %}

{% block title %}TODOS PRODUTOS{% endblock title %}

{% block content %}

<div class="container">

    <h2>TODOS OS PRODUTOS DA CATEGORIA</h2>
    <hr>
    {% for cat in todascategorias %}

    <h2>{{cat.titulo}}</h2>
    <div class="row mt-3">
        {% for p in cat.produto_set.all %}
        <div class="col-md-4">
            <div class="m-3">
                <h8><a href="{% url 'lojaapp:produtodetalhe' p.slug %}">{{p.titulo}}</h8></a>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 150px; object-fit: cover;">
                <P class="mt-3">Preço: <strike> R$ .{{p.mercado}}</strike> R$. {{p.venda}}</P>
                <a href="{% url 'lojaapp:addcarro' p.id%}" class="btn btn-success" >Adcionar ao Carrinho</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}